# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.6.8-slim

pipelines:
  default:
    - step:
        services:
          - docker
        name: test
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t pysleep .
          # authenticate with the Docker Hub registry
          - docker run pysleep 
